BlakeBananaWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlakeBananaWeb.Data;
using BlakeBananaWeb.Models;

namespace BlakeBananaWeb.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin
        public IActionResult Index()
        {
            IEnumerable<Product> ProductList = _context.Product;
            return View(ProductList);
        }

        // GET: Admin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var products = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // GET: Admin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product products)
        {
            if (ModelState.IsValid)
            {
                _context.Add(products);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Admin/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var products = _context.Product.Find(id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        //POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Product products)
        {

            if (ModelState.IsValid)
            {

                _context.Product.Update(products);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Admin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var products = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Products'  is null.");
            }
            var products = await _context.Product.FindAsync(id);
            if (products != null)
            {
                _context.Product.Remove(products);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return (_context.Product?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BlakeBananaWeb/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using BlakeBananaWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http.Extensions;
using Newtonsoft.Json;
using System.Web.Helpers;
using BlakeBananaWeb.Data;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace BlakeBananaWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly PurchaseDb _purchaseDb;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public CartController(ApplicationDbContext context, PurchaseDb purchaseDb, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _purchaseDb = purchaseDb;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("cart") == null)
            {
                List<Item> cart = new List<Item>();
                ViewBag.Cart = cart;
            }
            else
            {
                var cartObj = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("cart"));
                ViewBag.Cart = cartObj;
            }

            return View();
        }

        public ActionResult Buy(Product product)
        {
            if (HttpContext.Session.GetString("cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item { Products = product, Quantity = 1 });
                HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(cart));
            }
            else
            {
                var cartObj = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("cart"));
                int index = isExist(product.Id);
                if (index != -1)
                {
                    cartObj[index].Quantity++;
                }
                else
                {
                    cartObj.Add(new Item { Products = product, Quantity = 1 });
                }
                HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(cartObj));
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            var cartObj = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("cart"));

            int index = isExist(id);
            cartObj.RemoveAt(index);
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(cartObj));
            return RedirectToAction("Index");
        }

        public ActionResult ChangeQty(int id, int num)
        {
            var cartObj = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("cart"));
            int index = isExist(id);
            if (index != -1)
            {
                var change = cartObj[index].Quantity + num;
                var prod = cartObj[index].Products;
                cartObj.RemoveAt(index);
                if (change != 0)
                {
                    cartObj.Add(new Item { Products = prod, Quantity = change });
                }
            }
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(cartObj));
            return RedirectToAction("Index");
        }

        public ActionResult Checkout()
        {
            var Id = "";
            if (HttpContext.Session.GetString("cart") == null)
            {
                List<Product> products = new List<Product>();
                products = _context.Product.ToList();
                Random random = new Random();
                var shuffled = products.OrderBy(p => random.Next()).ToList();
                shuffled.RemoveRange(4, (products.Count - 4));
                ViewBag.Products = shuffled;
                return View("Empty");
            }
            else
            {
                var cartObj = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("cart"));
                if (_signInManager.IsSignedIn(User))
                {
                    Id = _userManager.GetUserId(User);
                }
                else
                {
                    Random random = new Random();
                    Id = random.Next().ToString();
                }
                foreach (Item item in cartObj)
                {
                    Purchase purchase = new Purchase()
                    {
                        ProductId = item.Products.Id,
                        Quantity = item.Quantity,
                        UserId = Id,
                        CreatedDate = DateTime.Now,
                    };
                    Purchase(purchase);
                }
                HttpContext.Session.Remove("cart");
                return View("Checkout");
            }

        }


        public int Purchase(Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                _purchaseDb.Add(purchase);
                _purchaseDb.SaveChanges();
            }
            else
            {
                return 1;
            }
            return 0;
        }

        private int isExist(int id)
        {
            List<Item> cart = JsonConvert.DeserializeObject<List<Item>>(HttpContext.Session.GetString("cart"));
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Products.Id.Equals(id))
                    return i;
            return -1;
        }


    }
}

BlakeBananaWeb/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore;
using Microsoft.EntityFrameworkCore;
using BlakeBananaWeb.Data;
using BlakeBananaWeb.Models;

namespace BlakeBananaWeb.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.Product != null ?
                        View(await _context.Product.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Products'  is null.");
        }
        public async Task<IActionResult> ViewProduct(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var products = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }
    }
}

BlakeBananaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blake's Bananas</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlakeBananaWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img id="logo" src="~/images/logo.png"/>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">All Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <a class="nav-link text-dark cart" asp-area="" asp-controller="Cart" asp-action="Index"><i class="bi bi-basket-fill"></i></a>
                </div>
            </div>
        </nav>
        
    </header>
    
    <div class="container">
        
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Blake's Bananas - <a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>